Refactored code with if statements

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -3,7 +3,7 @@
 set -e
 
 # Version number
-VERSION="2.2.2"
+VERSION="2.2.4"
 
 # Name of file currently run
 FILE="${0##*/}"
@@ -130,24 +130,13 @@ main() {
         esac
     done
     cd $NOTES_DIR
-    if [[ $(isNum "$y") == 1 ]]; then 
-        enterDirectory "Year$y"
-    elif [[ $y != "" ]]; then
-        echo "Error the $y flag must be specified as a number"
-    fi
-    if [[ $(isNum "$s") == 1 ]]; then
-        enterDirectory "Sem$s"
-    elif [[ $s != "" ]]; then 
-        echo "Error the $s flag must be specified as a number"
-    fi 
+    [[ $(isNum "$y") == 1 ]] && enterDirectory "Year$y" || echo "Error the $y flag must be specified as a number"
+    [[ $(isNum "$s") == 1 ]] && enterDirectory "Sem$s" || echo "Error the $s flag must be specified as a number"
     [[ $d != "" ]] && enterDirectory "$d"
     [[ $l == "list" ]] && ls --color
-    if [[ $p != "" ]]; then
-         makepdf $p
-        [[ $o == "open" ]] && zathura $p.pdf &
-    fi
+    [[ $p != "" ]] && makepdf $p ; [[ $o == "open" ]] && zathura $p.pdf &
     [[ $O != "" ]] && zathura $O.pdf &
-    unset y d p s l o
+    unset y d p s l o O
 }
 
 # envokes main
